from __future__ import annotations

from .scene import BoundingBox


CANVAS_WIDTH = 7168
CANVAS_HEIGHT = 4562

LEFT_MARGIN = 400
TOP_MARGIN = 300
RIGHT_PANEL_WIDTH = 1600
BOTTOM_MARGIN = 250

CONTENT_BOX = BoundingBox(
    LEFT_MARGIN,
    TOP_MARGIN,
    CANVAS_WIDTH - RIGHT_PANEL_WIDTH,
    CANVAS_HEIGHT - BOTTOM_MARGIN,
)
RIGHT_PANEL_BOX = BoundingBox(CANVAS_WIDTH - RIGHT_PANEL_WIDTH, 0, CANVAS_WIDTH, CANVAS_HEIGHT)
FRAME_BOX = BoundingBox(324, 193, 6845, 4368)
NOTES_BOX = BoundingBox(5620, 220, 6815, 3310)
REVISION_BOX = BoundingBox(5620, 3310, 6815, 3565)
TITLE_BLOCK_BOX = BoundingBox(5620, 3565, 6815, 4335)

PAPER_RGB = (199, 198, 198)
INK_RGB = (18, 18, 18)
MUTED_RGB = (55, 55, 55)
PANEL_RGB = (238, 238, 238)
WHITE_RGB = (250, 250, 250)

SVG_PAPER = "#c7c6c6"
SVG_INK = "#121212"
SVG_MUTED = "#373737"
SVG_PANEL = "#eeeeee"
SVG_WHITE = "#fafafa"

FONT_FAMILY = "DejaVu Sans Mono, monospace"

NOTE_TEMPLATES = [
    "PLEASE NOTE EVERY DATA PROVIDED HERE IS RANDOMLY GENERATED.",
    "CROSS-CHECKING AT CRITICAL SITES NEAR EFGH VALVES IS COMPULSORY.",
    "ALL FIXTURES ARE VALIDATED AND COMPLIANT WITH XYZ.",
    "TOP CONNECTION.",
    "FOR GENERAL NOTES AND LEGENDS SEE THE DWG-1.23.23.456 SERIES.",
    "ELEVATION ARE TO CENTER LINES UNLESS OTHERWISE NOTED.",
    "FOLLOWING XYZ SCHEMES ARE REQUIRED. SEE ABC DWG-1.23.45.67.89.",
    "ALL DIMENSIONS SHALL BE VERIFIED BY XYZ CONTRACTORS BEFORE WORK.",
    "TEMPERATURE CONTROL IS SET TO ON/OFF TYPE BY DEFAULT.",
    "COMPONENTS ARE AT NORMAL PRESSURE WITH POWER RATINGS 15.4 KWh.",
    "PQR VALVE TO BE INSTALLED AT 0 POINT.",
    "ORIENTATION OF ABCD VALVES SHALL BE VERIFIED AND CORRECTED AT SITE.",
    "BUILDING TO BE IN THE SLANTING PLANE THROUGH THE AXIS OF PQRS TYPE VALVES.",
    "FOR MAINTENANCE, ABCD VALVES ARE ACCESSIBLE FOR INSPECTION.",
    "ALL INSTALLATIONS SHALL BE VERIFIED BEFORE STARTUP OPERATIONS.",
    "DELETED.",
]

INSTRUMENT_CODES = [
    "RO-10",
    "DDL",
    "SDL",
    "ZLC",
    "LIC",
    "FIT",
    "PIT",
    "STA",
    "GLR",
    "TIC",
]

VALVE_CODES = ["AV", "DV", "GH", "MN", "QR", "KL", "WX", "RV", "UV", "IJ"]
GENERAL_CODES = ["CS", "STA", "LG-10", "INS", "MI", "OP", "AB", "CD", "EF", "MN"]
PIPE_CODES = ["ES", "GD", "NL", "OJ", "JJ", "EK", "CK", "FW", "HP", "CS"]
UNIT_CODES = ["CVCS", "IPY", "AI", "WPS", "RWS", "CAS", "SMP", "PFD"]
